### ISSUE TITLE
Just reinstalled with latest version in Chrome. Mocks no longer working.

### ISSUE THREAD

**Issue by apapajohn** [mukuljainx/Mokku#117] opened 2023-08-24 21:31 UTC
I just installed the latest version of this wonderful tool, but sadly it's no longer working. Reproduction steps:
1. Install latest Mokku
2. Run front end
3. In Mokku's Logs window, select "Mock" on one of the backend requests. In the dialog, change the request's Status from a 200 to a 500, in an attempt to simulate a failure.
4. Click "Add Mock" to save.
5. Run the front end again

Result: In the Mokku Logs window, it appears that the mocked request was mocked, because the left-most icon is blue, indicating that it was a "Mock" and not a "Network" request. But otherwise it doesn't seem to really have been mocked, because the response is still a 200.

I went back in and changed the response body in the mock, but then when I reloaded the front end, the response body still seemed to be coming from the network.

I tried these steps on a GET and a PUT

**Comment by apapajohn** [comment] 2023-08-24 21:47
Looks like it still works great in Edge.

**Comment by mukuljainx** [comment] 2023-08-25 03:28
Hi @apapajohn , thanks for reporting this. Was there any error on the console panel? can also try with different response?

**Comment by helenakrasnova** [comment] 2023-08-25 09:35
Hi!
doesn't work for me too in Chrome. Mokku has just empty tab both for localhost and for websites. 
Works good in MS Edge.

**Comment by apapajohn** [comment] 2023-08-25 17:18
There were no console errors. I did try changing the repsonse body in the mock, but that seems to have no effect. I just get the response from the actual service endpoint, even though in the Mokku logs it says that the response was the mocked one.

**Comment by mukuljainx** [comment] 2023-08-26 16:51
Thanks @apapajohn , thanks for reporting it. It should be fixed in 2.0.1

**Comment by mukuljainx** [comment] 2023-08-26 16:51
Hi @helenakrasnova what do you mean by empty tab? nothing renders there? can you please attach a screenshot, thankyou!

**Comment by Joustin** [comment] 2023-08-28 17:36
We're also seeing weird behavior in Chrome using newest version of 2.0.1
When running **local build**, we see a TypeError.

`TypeError
Cannot convert undefined or null to object
at Function.keys (<anonymous>)
    at t.getHeaders (inject.js:1:7795)
    etc etc
`

Mokku panel is completely blank

**Comment by mukuljainx** [comment] 2023-08-29 04:24
thanks @Joustin, Can you share your chrome version as well? for me both local and prod build are working I am on Version 116.0.5845.110 (Official Build) (arm64)

**Comment by apapajohn** [comment] 2023-08-29 14:08
Version 116.0.5845.111 (Official Build) (64-bit)z
on Windows

**Comment by apapajohn** [comment] 2023-08-29 14:17
Actually, Mokku seems to be working perfectly in my current version of Chrome now. Chrome did update when I went in to check the version. Maybe that fixed it. Chrome bug, perhaps?

This is a brilliant tool. Thanks for looking into this.

**Comment by mukuljainx** [comment] 2023-08-30 17:11
Hope you liking the new UI @apapajohn! 🥳 

@Joustin thanks for such detailed info, let me once check the code, if it can crash for any possbile reason, meanwhile can you try this in incognito mode? with only mokku enabled

**Comment by mukuljainx** [comment] 2023-08-30 17:11
@apapajohn can you review the tool in the chrome store, thanks! :)

**Comment by apapajohn** [comment] 2023-09-01 18:15
> Hope you liking the new UI @apapajohn! 🥳
> 
> @Joustin thanks for such detailed info, let me once check the code, if it can crash for any possbile reason, meanwhile can you try this in incognito mode? with only mokku enabled

Looks great!

**Comment by mukuljainx** [comment] 2023-09-02 15:35
Hi @Joustin, did some changes that might help you from the screenshot it's only clear there is some error in `getHeader` but not the cause. I have added sentry as well, so I can have a better picture of every error. Please try once Mokku with no ad blocker as it blocks the sentry. Thanks for your patience.

**Comment by Joustin** [comment] 2023-09-05 15:15
Thanks @mukuljainx .... Just checked and we're good!  I can see our local env working with latest Mokku 2.0.4!
Great work! and many thanks for such a cool product

**Closed** 2023-09-05 17:14 UTC
