### ISSUE TITLE
Mokku is replacing window.FormData with an incompatible API, thus breaking webpages

### ISSUE THREAD

**Issue by FirstWhack** [mukuljainx/Mokku#93] opened 2022-12-13 17:39 UTC
Expected behaviour: Instantiating FormData should return an instance of the native FormData, or something which extends it.

![Screenshot 2022-12-13 at 12 35 32 PM](https://user-images.githubusercontent.com/4481831/207405589-a7a3f2bb-ccb0-4bb2-8a3a-b1cdc9f88c74.png)

Actual behaviour: Mokku replaces FormData with an incompatible API, placing the actual FormData instance under `new FormData().fd`

![Screenshot 2022-12-13 at 12 38 02 PM](https://user-images.githubusercontent.com/4481831/207405221-d6aea9a2-6d0d-43f8-b204-fb4970c58f16.png)

The site-breaking code comes from chrome-extension://llflfcikklhgamfmnjkgpdadpmdplmji/js/inject.js

**Comment by joelmalone** [comment] 2023-03-27 02:02
Can confirm the same. For me it affected `FormData.entries()`.

This is on Chrome Version 111.0.5563.64 (Official Build) (arm64).

With Mokku extension disabled:

<img width="215" alt="image" src="https://user-images.githubusercontent.com/4830204/227822861-71f31a20-4b20-4433-afa8-b8ae46b51401.png">

With Mokku extension enabled:

<img width="173" alt="image" src="https://user-images.githubusercontent.com/4830204/227822822-1d624095-3450-486c-b036-0e301441189a.png">

**Comment by joelmalone** [comment] 2023-03-27 02:03
Just saw that this is a duplicate of #40.

**Comment by FirstWhack** [comment] 2023-03-28 16:09
Nice catch @joelmalone.

**Comment by mukuljainx** [comment] 2023-04-18 16:58
Hi everyone, thanks for raising this up, this seems to be fixed in xhook. I will be publishing new Mokku version soon. Have updated a lot of libraries and manifests, testing it out.

**Closed** 2023-08-27 12:59 UTC
